### ISSUE TITLE
[frontend] user name isn't saving from register page

### ISSUE THREAD

**Issue by abdulmoizeng** [recurship/event-manager#119]

**Comment by JavaEria** [comment]
@mashhoodr @abdulmoizeng the first name and last name is not being saved during signup in the backend and we are trying to display the fullname in the user profile page.

**Comment by abdulmoizeng** [comment]
@JavaEria  I have added those field in serializer. Please verify on branch **issue/119** 

Could you please update post man docs with signup api call ?

**Comment by JavaEria** [comment]
@mashhoodr @abdulmoizeng PR with updated postman collection
