### ISSUE TITLE
[backend] Configure forms properly on events

### ISSUE THREAD

**Issue by mashhoodr** [recurship/event-manager#169]
We need to be able to configure forms on our events. These forms can be used for multiple purposes like "registration", "call_for_papers", "call_for_mentors", etc. These forms are dynamic, so they can have any number of fields, with custom labels, limited types (text or textarea) and position. Each event will have a property "forms" which will be a dictionary the key being the purpose and the value being the reference to the form object. Admins will create the forms in the admin panel. Users attending the events will fill forms on frontend and submit their responses. Admins can then see the response in the admin panel.

Your task is to update the events model, create the forms models and ability to manage them in the admin panel (create forms and manage them) and the API to fetch form details and submit responses when users fill them.

If there is any confusion please ask here.

**Comment by saadullahaleem** [comment]
Got it. I think the right approach to take here would be to extend the JSONField class to support validation against a defined schema and use it for fields. I'm a little confused about the "form" property. Shouldn't we use standard SQL relations for this purpose?

**Comment by mashhoodr** [comment]
yes form property will contain the relation only. JSONField should work in this case.

**Comment by mashhoodr** [comment]
@saadullahaleem any udpate?

**Comment by mashhoodr** [comment]
@saadullahaleem please create the PR by tonight, we need to use this for our open source session tomorrow.

**Comment by mashhoodr** [comment]
tests can be added in a followup PR
