### ISSUE TITLE
[Backend] Event-update is breaking

### ISSUE THREAD

**Issue by usmandap** [recurship/event-manager#175]
Currently event update is not working, probably this may be due to some new added fields in the model which are comments or tags. Error is:
```
The `.update()` method does not support writable nested fields by default.
Write an explicit `.update()` method for serializer `event.serializers.EventSerializer`, or set `read_only=True` on nested serializer fields.
```

Note: Event update using update endpoint is not working, from django admin it is working.

**Comment by abdulmoizeng** [comment]
@usmandap  could you please point ot recreation steps? I am able to edit events

**Comment by usmandap** [comment]
@abdulmoizeng I am getting the above error.

**Comment by usmandap** [comment]
@abdulmoizeng I am not talking about event update update from django admin panel.

**Comment by abdulmoizeng** [comment]
I need to assess and test all event update related features

**Comment by abdulmoizeng** [comment]
@usmandap please test this and close this issue if its all fixed now

**Comment by usmandap** [comment]
I had opened a pr for event update here https://github.com/recurship/event-manager/pull/180
As I already told the fix you made by mentioning read-only=True on event serializer won't work with the many to many fields. I had fixed it in the above pr now event is successfully updating including many to many fields.
