### ISSUE TITLE
[frontend] Minor fixes 

### ISSUE THREAD

**Issue by mashhoodr** [recurship/event-manager#178]
- Initial page should be /events, currently opens /login
- Remove the welcoem to event management banner
- in event list whole card should be clickable
- in event details
 - event summary link overlaps next item
- in organisation details
 - empty icons, if a detail is missing icon shouldnt show

**Comment by taleymirza** [comment]
first task has already solved

**Comment by taleymirza** [comment]
second task will be done by @JavaEria in #209

**Comment by smkamranqadri** [comment]
all done.
