### ISSUE TITLE
[frontend/backend]: Fix Codacy issues

### ISSUE THREAD

**Issue by mashhoodr** [recurship/event-manager#20]
https://app.codacy.com/app/mashhoodr/event-manager/issues

**Comment by QaseemLodhi** [comment]
@mashhoodr can I take this one for now?

**Comment by JavaEria** [comment]
Do we need to fix the Prohibit console messages issue as i think we are in development mode so we would require console log messages?

**Comment by mashhoodr** [comment]
Yes you can leave the console logs

**Comment by mashhoodr** [comment]
Most of the issues are fixed
