### ISSUE TITLE
[backend] not able to select mutiple tag when creating or editing event

### ISSUE THREAD

**Issue by smkamranqadri** [recurship/event-manager#216]
While creating or editing the event, in the tag section, not able to select multiple tags/

**Comment by ZenabKhan** [comment]
@smkamranqadri you can select multiple tags.
Press command/ctrl key and select multiple tags

**Comment by smkamranqadri** [comment]
Then we need to add small text below that to select multiple tag use ctrl+click

**Comment by ZenabKhan** [comment]
@smkamranqadri it already shows a text:
<img width="780" alt="screenshot 2018-12-08 at 12 57 14 pm" src="https://user-images.githubusercontent.com/15312390/49683582-59758c80-fae9-11e8-9753-bf8899850478.png">

**Comment by smkamranqadri** [comment]
My bad then! :-)
